config/routes.rb
Rails.application.routes.draw do

  resources :rental_bookings
  resources :countries
  resources :contacts
  resources :calendars do
    member do
      get :export
    end
  end

#####################################
# begin preview namespace
#####################################
  namespace :preview do

  end

#####################################
# begin admin namespace
#####################################

  namespace :admin do
    get '/' => 'admins#index'
    get 'login' => 'admin_sessions#new'
    get 'documents/(:document_url)' => 'documents#show', :document_url => /\S+/
    get 'documents' => 'documents#index'
    resources :admin_addresses
    resources :admins
    resources :admins_sites
    resources :admin_sessions
    resources :article_posts do
      collection do
        post 'sort'
      end
    end
    resources :articles do
      member do
        patch 'category'
      end
    end
    resources :authors
    resources :article_authors
    resources :artists
    resources :admins_sites
    resources :blog_posts do
      collection do
        post 'sort'
      end
    end
    resources :blogs do
      member do
        patch 'category'
      end
    end
    resources :bookings
    resources :booking_transactions
    resources :calendars do
      member do
        get :import
      end
    end
    resources :carousels
    resources :carousel_slides do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :categories do
      member do
        patch 'image'
      end
      member do
        patch 'article'
      end
    end
    resources :content_group_clones, only: [:new,:create]
    resources :content_groups do
      member do
        patch 'category'
      end
    end
    resources :content_admins do
      collection do
        post 'sort'
      end
    end
    resources :content_group_items do
      collection do
        post 'sort'
      end
    end
    resources :content_group_text_items do
      collection do
        post 'sort'
      end
    end
    resources :container_clones, only: [:new,:create]
    resources :containers
    resources :containers_pages do
      collection do
        post 'sort'
      end
    end
    resources :container_rows do
      collection do
        post 'sort'
      end
    end
    resources :designers
    resources :domains
    resources :dropdowns
    resources :dropdown_items do
      collection do
        post 'sort'
      end
    end
    resources :errors
    resources :images do
      member do
        patch 'category'
      end
    end
    resources :image_batches
    resources :image_batch_images
    resources :image_batch_uploads, only: [:create]
    resources :image_crops
    resources :image_optimizations
    resources :image_previews
    resources :image_publishes, only: [:create]
    resources :image_watermarks
    resources :image_groups
    resources :image_group_items do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :image_group_uploads
    resources :list_group_items do
      collection do
        post 'sort'
      end
    end
    resources :list_group_clones, only: [:new,:create]
    resources :list_groups
    resources :mail_servers
    resources :mail_templates
    resources :media  do
      member do
        patch 'category'
      end
    end
    resources :navigation_items do
      collection do
        post 'sort'
      end
    end
    resources :navigations
    resources :palettes
    resources :palette_colors
    resources :pages
    resources :payment_gateways
    resources :payment_methods
    resources :payment_types
    resources :rental_booking_instructions
    resources :rental_payment_methods do
      collection do
        post 'sort'
      end
    end
    resources :rentals
    resources :row_columns do
      collection do
        post 'sort'
      end
    end
    resources :site_tags do
      collection do
        post 'sort'
      end
    end
    resources :sites
    resources :songs
    resources :themes do
      member do
        get 'edit_scss_production'
      end
      member do
        get 'edit_scss_workspace'
      end
      member do
        put 'sync_css'
      end
    end
    resources :theme_colors
    resources :theme_icons
    resources :user_addresses
    resources :users
    resources :videos
    resources :watermarks
  end

  #####################################
  # end admin namespace
  #####################################

  resources :media
  resources :posts
  resources :artists
  resources :authors
  resources :errors
  resources :images
  resources :users

  # Added to match before :nice_url for pages
  get '/rails/active_storage/blobs/:signed_id/*filename(.:format)' => 'active_storage/blobs#show'
  get '/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)' => 'active_storage/representations#show'
  get '/rails/active_storage/disk/:encoded_key/*filename(.:format)' => 'active_storage/disk#show'
  put '/rails/active_storage/disk/:encoded_token(.:format)' => 'active_storage/disk#update'
  post '/rails/active_storage/direct_uploads(.:format)' => 'active_storage/direct_uploads#create'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/articles' => 'articles#index'
  get '/articles/(:content_url)' => 'articles#show', :content_url => /\S+/
  get '/image_previews/*' => 'pages#static_asset'
  get '/documents/*' => 'pages#static_asset'
  get '/(:nice_url)' => 'pages#show', :nice_url => /\S+/
  root 'pages#show'

end

app/models/container_row.rb
class ContainerRow < ApplicationRecord
	belongs_to :container
	has_many :row_columns, -> { order('position ASC') }

	before_save :prepend_row
	before_create :set_position

	def added_css_classes
		self.css_classes.sub(/^row\s/,'')
	end

	def prepend_row
		self.css_classes = "row #{self.added_css_classes}"
	end

	def set_position
		self.position = ContainerRow.where(container_id: self.container_id).count + 1
	end


end

app/controllers/admin/container_rows_controller.rb
class Admin::ContainerRowsController < AdminController
	before_action :set_container_row, only: [:show, :edit, :update, :destroy]
  before_action :set_new, only: [:new]

	layout 'admins'

  def sort
    params[:container_row].each_with_index do |id, index|
      item = ContainerRow.find(id)
      item.update_attribute(:position, index + 1) if item
    end
    render body: nil
  end

  # GET /container_rows
  # GET /container_rows.json
  def index
    @container_row = nil
    @container_rows =  @container ? ContainerRow.where(container_id: @container.id).order("position asc") : Container.where(site_id: @site.id)
  end

  # GET /container_rows/1
  # GET /container_rows/1.json
  def show
    @row_columns = @container_row.row_columns
  end

  # GET /container_rows/new
  def new
    @container_row = ContainerRow.new
    @container_row.container = @container
  end

  # GET /container_rows/1/edit
  def edit
  end

  # POST /container_rows
  # POST /container_rows.json
  def create
    @container_row = ContainerRow.new(container_row_params)
    respond_to do |format|
      if @container_row.save
        flash[:success] = 'Row was successfully created.'
        format.html { redirect_to admin_container_row_url(@container_row) }
        format.json { render :show, status: :created, location: @container_row }
      else
        set_new
        format.html { render :new }
        format.json { render json: @container_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /container_rows/1
  # PATCH/PUT /container_rows/1.json
  def update
    respond_to do |format|
      if @container_row.update(container_row_params)
        flash[:success] = 'Row was successfully updated.'
        if @page
          format.html { redirect_to admin_page_url(@page) }
        else
          format.html { redirect_to admin_container_row_url(@container_row) }
        end
        format.json { render :show, status: :ok, location: @container_row }
      else
        format.html { render :edit }
        format.json { render json: @container_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /container_rows/1
  # DELETE /container_rows/1.json
  def destroy
    @container = @container_row.container
    @container_row.destroy
    respond_to do |format|
      flash[:success] = 'Row was successfully deleted.' 
      format.html { redirect_to admin_container_url(@container) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
     def set_new
       @container = Container.find(params[:container_id])
       @container_row = ContainerRow.new
     end

    def set_container_row
      @container_row = ContainerRow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_row_params
      params.require(:container_row).permit(:name,:container_id,:css_classes)
    end
end

app/views/admin/container_rows/_form.html.erb
<% if @container_row.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
		<%= pluralize(@container_row.errors.count, "error") %> prohibited this page from being saved:
	</div>
  <ul>
  <% @container_row.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :container_id %>


<div class="form-group">
	<label for="container_row_css_classes"><%= f.label :css_classes, "CSS space separated class names (row automatically included)" %></label>
	<div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="inputGroup-sizing-default">row</span>
    </div>
    <%= f.text_field :css_classes, value:  @container_row.css_classes ? @container_row.added_css_classes : '', :class => "form-control" %>
  </div>
</div>

app/views/admin/container_rows/_index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
		  <h2>Rows</h2>
		</div>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Position</th>
					<th>Row</th>
					<th>CSS</th>
					<th>Columns/CSS</th>
					<th>Columns/Content</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody id="container_rows" data-sort-items-url="<%= sort_admin_container_rows_url %>">
<% @container_rows.each do |container_row| %>
				<tr class="container_row" id="container_row_<%= container_row.id %>">
					<td><span class="handle"><i class="icon-up-hand"></i></span></td>
          <td><%= link_to "Row #{container_row.position}", admin_container_row_path(container_row) %></td>
          <td><%= link_to raw(container_row.css_classes), admin_container_row_path(container_row) %></td>
  <%
		i = 1
	  column_css = ""
  	content_type = ""
  	content = ""
  	link = ""
  	container_row.row_columns.each do |col|
  		content_type = col.content_type
  		column_css += link_to raw("#{i}.) #{col.css_classes} <icon class=\"icon-pencil\"></icon>"), edit_admin_row_column_url(col), target: "column_#{col.id}"
  		content += "#{i}.) "
  		case col.content_type
  		when 'carousel'
   			content += link_to raw("#{col.carousel.name} <icon class=\"icon-right-hand\"></icon>"), admin_carousel_url(col.carousel), target: "#{content_type}?#{rand(10000000)}"
  		when /image_group|image_grid/
   			content += link_to raw("#{col.image_group.name} <icon class=\"icon-right-hand\"></icon>"), admin_image_group_url(col.image_group), target: "#{content_type}?#{rand(10000000)}"
  		when 'list_group'
   			content += link_to raw("#{col.list_group.name} <icon class=\"icon-right-hand\"></icon>"), admin_list_group_url(col.list_group), target: "#{content_type}?#{rand(10000000)}"
   		when 'content_group'
   			content += link_to raw("#{col.content.name} <icon class=\"icon-right-hand\"></icon>"), admin_content_group_url(col.content), target: "#{content_type}?#{rand(10000000)}"
  		else
  			content = "#{col.inspect}"
  		end
  		column_css += "<br/>"
  		content += "<br/>"
  		i += 1
  	end
  %>
  				<td><%= raw(column_css) %></td>
  				<td><%= link_to raw(content), link, target: "#{content_type}?#{rand(4)}" %></td>
          <td><%= link_to raw('<i class="icon-zoom-in"></i>'), admin_container_row_path(container_row) %></td>
          <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_admin_container_row_path(container_row) %></td>
          <td><%= link_to raw('<i class="icon-trash"></i>'), admin_container_row_path(container_row), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
<% end %>
				<%= raw('<tr><td colspan="6">No items for this list</td></tr>') unless @container_rows.count > 0 %>
			</tbody>
		</table>
		<%= link_to new_admin_container_row_path(container_id: @container.id) do %>
			<button type="button" class="btn  btn-outline-secondary btn-med"><i class="icon-plus"></i> New Row</button>
		<% end %>
	</div>
</div>

app/views/admin/container_rows/edit.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>Edit Row <%= @container_row.position %></h1>
		</div>
		<%= form_for([:admin, @container_row],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Save
			<% end %>
<% if @page %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_page_path(@page)) %>
<% else %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_container_row_path(@container_row)) %>
<% end %>		
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@container_row,[@container_row.container]) %>
	</div>
</div>

app/views/admin/container_rows/new.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>New Row</h1>
		</div>
		<%= form_for([:admin, @container_row],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Create
			<% end %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_container_path(@container)) %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@container_row,[@container]) %>
	</div>
</div>

app/views/admin/container_rows/show.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
			<h1><%= @container_row.container.name %> Row <%= @container_row.position %></h1>
		</div>	
		<%= object_table(@container_row) %>
		<%= link_to edit_admin_container_row_path(@container_row) do %>
			<button type="submit" class="btn  btn-outline-secondary"><i class="icon-pencil"></i> Edit</button>
		<% end %>
		&nbsp;&nbsp;<%= link_to admin_container_row_path(@container_row), method: :delete, data: { confirm: "Delete container_row?" } do %>
			<button type="submit" class="btn btn-danger"><i class="icon-trash"></i> Delete</button>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@container_row,[@container_row.container]) %>
	</div>
</div>
<hr/>
<%= render partial: 'admin/row_columns/index' %>