config/routes.rb
Rails.application.routes.draw do

  resources :rental_bookings
  resources :countries
  resources :contacts
  resources :calendars do
    member do
      get :export
    end
  end

#####################################
# begin preview namespace
#####################################
  namespace :preview do

  end

#####################################
# begin admin namespace
#####################################

  namespace :admin do
    get '/' => 'admins#index'
    get 'login' => 'admin_sessions#new'
    get 'documents/(:document_url)' => 'documents#show', :document_url => /\S+/
    get 'documents' => 'documents#index'
    resources :admin_addresses
    resources :admins
    resources :admins_sites
    resources :admin_sessions
    resources :article_posts do
      collection do
        post 'sort'
      end
    end
    resources :articles do
      member do
        patch 'category'
      end
    end
    resources :authors
    resources :article_authors
    resources :artists
    resources :admins_sites
    resources :blog_posts do
      collection do
        post 'sort'
      end
    end
    resources :blogs do
      member do
        patch 'category'
      end
    end
    resources :bookings
    resources :booking_transactions
    resources :calendars do
      member do
        get :import
      end
    end
    resources :carousels
    resources :carousel_slides do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :categories do
      member do
        patch 'image'
      end
      member do
        patch 'article'
      end
    end
    resources :content_group_clones, only: [:new,:create]
    resources :content_groups do
      member do
        patch 'category'
      end
    end
    resources :content_admins do
      collection do
        post 'sort'
      end
    end
    resources :content_group_items do
      collection do
        post 'sort'
      end
    end
    resources :content_group_text_items do
      collection do
        post 'sort'
      end
    end
    resources :container_clones, only: [:new,:create]
    resources :containers
    resources :containers_pages do
      collection do
        post 'sort'
      end
    end
    resources :container_rows do
      collection do
        post 'sort'
      end
    end
    resources :designers
    resources :domains
    resources :dropdowns
    resources :dropdown_items do
      collection do
        post 'sort'
      end
    end
    resources :errors
    resources :images do
      member do
        patch 'category'
      end
    end
    resources :image_batches
    resources :image_batch_images
    resources :image_batch_uploads, only: [:create]
    resources :image_crops
    resources :image_optimizations
    resources :image_previews
    resources :image_publishes, only: [:create]
    resources :image_watermarks
    resources :image_groups
    resources :image_group_items do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :image_group_uploads
    resources :list_group_items do
      collection do
        post 'sort'
      end
    end
    resources :list_group_clones, only: [:new,:create]
    resources :list_groups
    resources :mail_servers
    resources :mail_templates
    resources :media  do
      member do
        patch 'category'
      end
    end
    resources :navigation_items do
      collection do
        post 'sort'
      end
    end
    resources :navigations
    resources :palettes
    resources :palette_colors
    resources :pages
    resources :payment_gateways
    resources :payment_methods
    resources :payment_types
    resources :rental_booking_instructions
    resources :rental_payment_methods do
      collection do
        post 'sort'
      end
    end
    resources :rentals
    resources :row_columns do
      collection do
        post 'sort'
      end
    end
    resources :site_tags do
      collection do
        post 'sort'
      end
    end
    resources :sites
    resources :songs
    resources :themes do
      member do
        get 'edit_scss_production'
      end
      member do
        get 'edit_scss_workspace'
      end
      member do
        put 'sync_css'
      end
    end
    resources :theme_colors
    resources :theme_icons
    resources :user_addresses
    resources :users
    resources :videos
    resources :watermarks
  end

  #####################################
  # end admin namespace
  #####################################

  resources :media
  resources :posts
  resources :artists
  resources :authors
  resources :errors
  resources :images
  resources :users

  # Added to match before :nice_url for pages
  get '/rails/active_storage/blobs/:signed_id/*filename(.:format)' => 'active_storage/blobs#show'
  get '/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)' => 'active_storage/representations#show'
  get '/rails/active_storage/disk/:encoded_key/*filename(.:format)' => 'active_storage/disk#show'
  put '/rails/active_storage/disk/:encoded_token(.:format)' => 'active_storage/disk#update'
  post '/rails/active_storage/direct_uploads(.:format)' => 'active_storage/direct_uploads#create'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/articles' => 'articles#index'
  get '/articles/(:content_url)' => 'articles#show', :content_url => /\S+/
  get '/image_previews/*' => 'pages#static_asset'
  get '/documents/*' => 'pages#static_asset'
  get '/(:nice_url)' => 'pages#show', :nice_url => /\S+/
  root 'pages#show'

end

app/models/navigation_item.rb
class NavigationItem < ApplicationRecord

	belongs_to :navigation
	belongs_to :page, optional: true
	belongs_to :category, optional: true
	belongs_to :list_group, optional: true
	belongs_to :link_text, optional: true
	belongs_to :dropdown, optional: true

	validates :name, presence: true
	validates :name, uniqueness: { scope: :navigation_id, message: " is in use for this navigation" }
	validates :label, presence: true
	
	attr_accessor :dropdown_css

	before_save :prepend_css

	def added_css_classes
		self.css_classes.sub(/^nav-item\s|dropdown\s/,'') if self.css_classes
	end

	def prepend_css
		nav_css = self.dropdown_css ? "nav-item dropdown" : "nav-item"
		self.css_classes = "#{nav_css} #{self.added_css_classes}"
	end


end

app/controllers/admin/navigation_items_controller.rb
class Admin::NavigationItemsController < AdminController
  before_action :set_navigation_item, only: [:show, :edit, :update, :destroy]
  before_action :set_new, only: [:new]

  layout 'admins'

  def sort
    params[:navigation_item].each_with_index do |id, index|
      item = NavigationItem.find(id)
      item.update_attribute(:position, index + 1) if item
    end
    render body: nil
  end

  # GET /navigation_items
  # GET /navigation_items.json
  def index
    @navigation_items = NavigationItem.all
  end

  # GET /navigation_items/1
  # GET /navigation_items/1.json
  def show
  end

  # GET /navigation_items/new
  def new

  end

  # GET /navigation_items/1/edit
  def edit
  end

  # POST /navigation_items
  # POST /navigation_items.json
  def create
    respond_to do |format|
      @navigation_item = NavigationItem.new(navigation_item_params)
      if params[:link_text].present?
        @navigation_item.link_text = LinkText.create!(link_text_params)
      end
      if params[:dropdown].present?
        @navigation_item.dropdown = Dropdown.create!(dropdown_params)
      end
      if @navigation_item.save
        flash[:success] = 'Navigation item was successfully created.'
        if @navigation_item.dropdown
          format.html { redirect_to new_admin_dropdown_item_url(dropdown_id: @navigation_item.dropdown_id) }
        else
          format.html { redirect_to admin_navigation_item_url(@navigation_item) }
        end
        format.json { render :show, status: :created, location: @navigation_item }
      else
        format.html { render :new }
        format.json { render json: @navigation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navigation_items/1
  # PATCH/PUT /navigation_items/1.json
  def update
    respond_to do |format|
      if params[:link_text].present?
        @navigation_item.link_text.update!(link_text_params)
      end
      if params[:dropdown].present?
        @navigation_item.dropdown.update!(dropdown_params)
      end
      if @navigation_item.update(navigation_item_params)
        flash[:success] = 'Navigation item was successfully updated'
        if @page
          format.html { redirect_to admin_page_url(@page) }
        else
          format.html { redirect_to admin_navigation_item_url(@navigation_item) }
        end
        format.json { render :show, status: :ok, location: @navigation_item }
      else
        format.html { render :edit }
        format.json { render json: @navigation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navigation_items/1
  # DELETE /navigation_items/1.json
  def destroy
    @navigation = @navigation_item.navigation
    @navigation_item.destroy
    respond_to do |format|
      flash[:success] = 'Navigation item was successfully deleted'
      format.html { redirect_to admin_navigation_url(@navigation) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navigation_item
      @navigation_item = NavigationItem.find(params[:id])
    end

    def set_new
      @navigation = Navigation.find(params[:navigation_id])
      @navigation_item = NavigationItem.new
      @navigation_item.navigation = @navigation
      @navigation_item.item_type = params[:item_type].present? ? params[:item_type] : nil
      @link_text = LinkText.new(site_id: @site.id,link: 'https://',http_https: 'https') if @navigation_item.item_type && @navigation_item.item_type =~ /external/
      @dropdown = Dropdown.new(site_id: @site.id) if @navigation_item.item_type && @navigation_item.item_type =~ /dropdown/
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navigation_item_params
      params.require(:navigation_item).permit(:name,:label,:navigation_id,:css_classes,:item_type,:page_id,:category_id,:link_text_id,:dropdown_css)
    end

    def link_text_params
      params.require(:link_text).permit(:site_id,:link,:body,:css_classes,:http_https,:new_window,:test_text)
    end

    def dropdown_params
      params.require(:dropdown).permit(:site_id,:name,:css_classes,:nav_type)
    end


end

app/views/admin/navigation_items/_form.html.erb
<% if @navigation_item.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
		<%= pluralize(@navigation_item.errors.count, "error") %> prohibited this page from being saved:
	</div>
  <ul>
  <% @navigation_item.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :navigation_id %>
<%= f.hidden_field :item_type %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :label %>
	<%= f.text_field :label, :class => "form-control" %>
</div>
<%= render partial: "form_#{@navigation_item.item_type}", locals: {f:f} %> 

app/views/admin/navigation_items/_form_category_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the navigation item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="container_row_css_classes"><%= f.label :css_classes %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @navigation.css_classes ? @navigation.added_css_classes : '', :class => "form-control" %>
</div>

<div class="form-bar">
	<%= f.label :category_id %>
	<%= f.select :category_id, Category.where(site_id: @site.id).order('name asc').collect { |c| [c.name, c.id] }, {prompt: 'Please Select'}, :class => "form-control" %>
</div>

app/views/admin/navigation_items/_form_dropdown.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the navigation item.</p> 
	<p>Classes nav-item and dropdown are automatically included.</p>
</div>
<label for="container_row_css_classes"><%= f.label :css_classes %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item dropdown</span>
  </div>
  <%= f.text_field :css_classes, value: @navigation_item.css_classes ? @navigation_item.added_css_classes : '', :class => "form-control" %>
</div>
<h3>New Dropdown Menu</h3>
<%= fields_for @dropdown do |dropdown| %>
	<%= dropdown.hidden_field :site_id %>
  <%= dropdown.hidden_field :nav_type, value: @navigation_item.navigation.nav_type %>
	<div class="form-group">
		<%= dropdown.label :name %>
		<%= dropdown.text_field :name, :class => "form-control" %>
	</div>
	<div class="bs-help">
		<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the dropdown menu.</p> 
		<p>Classes dropdown-menu is automatically included.</p>
	</div>	
 	<div class="form-group">
    <label for="link_text_link"><%= dropdown.label :css_classes %></label>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroup-sizing-default">
          dropdown-menu
        </span>
      </div>
      <%= dropdown.text_field :css_classes, value: @dropdown.css_classes ? @dropdown.added_css_classes : '', :class => "form-control" %>
    </div>
  </div>  
<% end %>

app/views/admin/navigation_items/_form_external_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the navigation item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="navigation_item_css_classes"><%= f.label :css_classes, "CSS space separated class names" %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @navigation_item.css_classes ? @navigation_item.added_css_classes : '', :class => "form-control" %>
</div>
<% @navigation_item.link_text = LinkText.new unless  @navigation_item.link_text %>
<%= fields_for @navigation_item.link_text do |link| %>
  <%= render partial: "admin/link_texts/form", locals: {link: link, link_text: @navigation_item.link_text } %>
<% end %>

app/views/admin/navigation_items/_form_page_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the navigation item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="container_row_css_classes"><%= f.label :css_classes %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @navigation_item.css_classes ? @navigation_item.added_css_classes : '', :class => "form-control" %>
</div>

<div class="form-bar"">
	<%= f.label :page_id %>
	<%= f.select :page_id, Page.where(site_id: @site.id).order('name asc').collect { |p| [p.name, p.id] }, {prompt: 'Please Select'}, :class => "form-control" %>
</div>

app/views/admin/navigation_items/_index.html.erb
<div class="row">
	<div class="col-md-12">
	  <h2>Navigation Items</h2>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Position</th>
					<th>Name</th>
					<th>Type</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody id="navigation_items" data-sort-items-url="<%= sort_admin_navigation_items_url %>">
<% @navigation_items.order('position asc').each do |navigation_item| %>
        <tr class="navigation_items" id="navigation_item_<%= navigation_item.id %>">
        	<td><span class="handle"><i class="icon-up-hand"></i></span></td>	
          <td><%= link_to raw(navigation_item.name), admin_navigation_item_path(navigation_item) %></td>
          <td><%= link_to navigation_item.item_type.capitalize.sub(/_/,' '), admin_navigation_item_path(navigation_item) %></td>
          <td><%= link_to raw('<i class="icon-zoom-in"></i>'), admin_navigation_item_path(navigation_item) %></td>
          <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_admin_navigation_item_path(navigation_item) %></td>
          <td><%= link_to raw('<i class="icon-trash"></i>'), admin_navigation_item_path(navigation_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
<% end %>
				<%= raw('<tr><td colspan="6">No items for this list</td></tr>') unless @navigation_items.count > 0 %>
			</tbody>
		</table>
		<%= link_to new_admin_navigation_item_path(navigation_id: @navigation.id) do %>
			<button type="button" class="btn  btn-outline-secondary btn-med"><i class="icon-plus"></i> New Navigation Item</button>
		<% end %>
	</div>
</div>

app/views/admin/navigation_items/edit.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>Edit <%= @navigation_item.name %></h1>
		</div>
		<%= form_for([:admin, @navigation_item],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Save
			<% end %>
<% if @page %> 
		<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_page_path(@page)) %>
<% else %>
		<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_navigation_item_path(@navigation_item)) %>
<% end %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@navigation_item) %>
	</div>
</div>

app/views/admin/navigation_items/index.html.erb
<%= render partial: 'index' %>

app/views/admin/navigation_items/new.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>New <%= @navigation_item.item_type ? @navigation_item.item_type.capitalize.sub(/_/,' ') : nil %> Navigation Item</h1>
		</div>
<% if @navigation_item.item_type %>
		<%= form_for([:admin, @navigation_item],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Create
			<% end %>
			<%= link_to new_admin_navigation_item_path do %>
				<button type="button" class="btn  btn-outline-secondary btn-med btn-right"><i class="icon-cancel"></i> Cancel</button>
			<% end %>
		<% end %>
<% else %>
		<div class="bs-help">
			<h3>Navigation Item types</h3>
			<div><p><strong>Page link: </strong>Creates a menu item for a specific page such as Home, About, Blog, etc.</p>
			<%= link_to new_admin_navigation_item_path(navigation_id: @navigation.id, item_type: 'page_link') do %>
				<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New Page Link Item</button>
			<% end %>
			</div>
			<hr/>
			<div><p><strong>Category link: </strong>Creates a menu item for a specific category.</p> 
				<%= link_to new_admin_navigation_item_path(navigation_id: @navigation.id, item_type: 'category_link') do %>
					<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New Category Link Item</button>
				<% end %>
			</div>
			<hr/>
			<div><p><strong>External link or text: </strong>Creates a menu item for an external link or some text.</p> 
				<%= link_to new_admin_navigation_item_path(navigation_id: @navigation.id, item_type: 'external_link') do %>
					<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New External Link Item</button>
				<% end %>
			</div>
			<hr/>
			<div><p><strong>Page link: </strong>Creates a custom dropdown menu item.</p> 
				<%= link_to new_admin_navigation_item_path(navigation_id: @navigation.id, item_type: 'dropdown') do %>
					<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New Dropdown Item</button>
				<% end %>
			</div>
			<hr/>
			<%= link_to admin_navigation_path(@navigation_item.navigation) do %>
				<button type="button" class="btn  btn-outline-secondary btn-med btn-right"><i class="icon-cancel"></i> Cancel</button>
			<% end %>
		</div>
	<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@navigation_item,[@navigation]) %>
	</div>
</div>

app/views/admin/navigation_items/show.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
			<h1><%= @navigation_item.name %></h1>
		</div>	
		<%= object_table(@navigation_item) %>
		<%= link_to edit_admin_navigation_item_path(@navigation_item) do %>
			<button type="submit" class="btn  btn-outline-secondary"><i class="icon-pencil"></i> Edit</button>
		<% end %>
		&nbsp;&nbsp;<%= link_to admin_navigation_item_path(@navigation_item), method: :delete, data: { confirm: "Delete navigation_item?" } do %>
			<button type="submit" class="btn btn-danger"><i class="icon-trash"></i> Delete</button>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@navigation_item,[@navigation_item.navigation]) %>
	</div>
</div>