config/routes.rb
Rails.application.routes.draw do

  resources :rental_bookings
  resources :countries
  resources :contacts
  resources :calendars do
    member do
      get :export
    end
  end

#####################################
# begin preview namespace
#####################################
  namespace :preview do

  end

#####################################
# begin admin namespace
#####################################

  namespace :admin do
    get '/' => 'admins#index'
    get 'login' => 'admin_sessions#new'
    get 'documents/(:document_url)' => 'documents#show', :document_url => /\S+/
    get 'documents' => 'documents#index'
    resources :admin_addresses
    resources :admins
    resources :admins_sites
    resources :admin_sessions
    resources :article_posts do
      collection do
        post 'sort'
      end
    end
    resources :articles do
      member do
        patch 'category'
      end
    end
    resources :authors
    resources :article_authors
    resources :artists
    resources :admins_sites
    resources :blog_posts do
      collection do
        post 'sort'
      end
    end
    resources :blogs do
      member do
        patch 'category'
      end
    end
    resources :bookings
    resources :booking_transactions
    resources :calendars do
      member do
        get :import
      end
    end
    resources :carousels
    resources :carousel_slides do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :categories do
      member do
        patch 'image'
      end
      member do
        patch 'article'
      end
    end
    resources :content_group_clones, only: [:new,:create]
    resources :content_groups do
      member do
        patch 'category'
      end
    end
    resources :content_admins do
      collection do
        post 'sort'
      end
    end
    resources :content_group_items do
      collection do
        post 'sort'
      end
    end
    resources :content_group_text_items do
      collection do
        post 'sort'
      end
    end
    resources :container_clones, only: [:new,:create]
    resources :containers
    resources :containers_pages do
      collection do
        post 'sort'
      end
    end
    resources :container_rows do
      collection do
        post 'sort'
      end
    end
    resources :designers
    resources :domains
    resources :dropdowns
    resources :dropdown_items do
      collection do
        post 'sort'
      end
    end
    resources :errors
    resources :images do
      member do
        patch 'category'
      end
    end
    resources :image_batches
    resources :image_batch_images
    resources :image_batch_uploads, only: [:create]
    resources :image_crops
    resources :image_optimizations
    resources :image_previews
    resources :image_publishes, only: [:create]
    resources :image_watermarks
    resources :image_groups
    resources :image_group_items do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :image_group_uploads
    resources :list_group_items do
      collection do
        post 'sort'
      end
    end
    resources :list_group_clones, only: [:new,:create]
    resources :list_groups
    resources :mail_servers
    resources :mail_templates
    resources :media  do
      member do
        patch 'category'
      end
    end
    resources :navigation_items do
      collection do
        post 'sort'
      end
    end
    resources :navigations
    resources :palettes
    resources :palette_colors
    resources :pages
    resources :payment_gateways
    resources :payment_methods
    resources :payment_types
    resources :rental_booking_instructions
    resources :rental_payment_methods do
      collection do
        post 'sort'
      end
    end
    resources :rentals
    resources :row_columns do
      collection do
        post 'sort'
      end
    end
    resources :site_tags do
      collection do
        post 'sort'
      end
    end
    resources :sites
    resources :songs
    resources :themes do
      member do
        get 'edit_scss_production'
      end
      member do
        get 'edit_scss_workspace'
      end
      member do
        put 'sync_css'
      end
    end
    resources :theme_colors
    resources :theme_icons
    resources :user_addresses
    resources :users
    resources :videos
    resources :watermarks
  end

  #####################################
  # end admin namespace
  #####################################

  resources :media
  resources :posts
  resources :artists
  resources :authors
  resources :errors
  resources :images
  resources :users

  # Added to match before :nice_url for pages
  get '/rails/active_storage/blobs/:signed_id/*filename(.:format)' => 'active_storage/blobs#show'
  get '/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)' => 'active_storage/representations#show'
  get '/rails/active_storage/disk/:encoded_key/*filename(.:format)' => 'active_storage/disk#show'
  put '/rails/active_storage/disk/:encoded_token(.:format)' => 'active_storage/disk#update'
  post '/rails/active_storage/direct_uploads(.:format)' => 'active_storage/direct_uploads#create'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/articles' => 'articles#index'
  get '/articles/(:content_url)' => 'articles#show', :content_url => /\S+/
  get '/image_previews/*' => 'pages#static_asset'
  get '/documents/*' => 'pages#static_asset'
  get '/(:nice_url)' => 'pages#show', :nice_url => /\S+/
  root 'pages#show'

end

app/models/dropdown_item.rb
class DropdownItem < ApplicationRecord

	belongs_to :dropdown
	belongs_to :page, optional: true
	belongs_to :category, optional: true
	belongs_to :link_text, optional: true

	validates :name, presence: true
	validate :check_dropdown_item_exclusive_arc

	attr_accessor :dropdown_item_css

	def added_css_classes
		self.css_classes.sub(/^nav-item\s/,'') if self.css_classes
	end

	def prepend_css
		self.css_classes = "nav-item #{self.added_css_classes}"
	end

  def check_dropdown_item_exclusive_arc
  	if self.item_type == 'page_link' and not self.page_id	
  		raise ExclusiveArcError.new("Page is required, please select")
  	elsif self.item_type == 'category_link' and not self.category_id	
  		raise ExclusiveArcError.new("Category is required, please select")
  	elsif self.item_type == 'external_link' and not self.link_text_id	
  		raise ExclusiveArcError.new("External link is missing")
  	else
  		true
  	end
  end

  class ExclusiveArcError < StandardError
  	def initialize(message)
  		@message = message
  	end
  	def message
  		@message
  	end
  end




end

app/controllers/admin/dropdown_items_controller.rb
class Admin::DropdownItemsController < AdminController
  before_action :set_dropdown_item, only: [:show, :edit, :update, :destroy]
  before_action :set_new, only: [:new]
 
  layout 'admins'

  def sort
    params[:dropdown_item].each_with_index do |id, index|
      item = DropdownItem.find(id)
      item.update_attribute(:position, index + 1) if item
    end
    render body: nil
  end

  # GET /dropdown_items
  # GET /dropdown_items.json
  def index
    @dropdown_items = DropdownItem.all
  end

  # GET /dropdown_items/1
  # GET /dropdown_items/1.json
  def show
  end

  # GET /dropdown_items/new
  def new

  end

  # GET /dropdown_items/1/edit
  def edit
  end

  # POST /dropdown_items
  # POST /dropdown_items.json
  def create
    @dropdown_item = DropdownItem.new(dropdown_item_params)
    respond_to do |format|
      begin
        if @dropdown_item.item_type == 'external_link'
          @dropdown_item.link_text = LinkText.create(link_text_params)
        end
        @dropdown_item.save!
        flash[:success] = 'dropdown item was successfully created.'
        format.html { redirect_to admin_dropdown_item_url(@dropdown_item) }
        format.json { render :show, status: :created, location: @dropdown_item }
      rescue Exception, DropdownItem::ExclusiveArcError => e
        flash[:danger] = "Error: #{e.message}"
        format.html { render :new }
        format.json { render json: @dropdown_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dropdown_items/1
  # PATCH/PUT /dropdown_items/1.json
  def update
    respond_to do |format|
      begin 
        @dropdown_item.update(dropdown_item_params)
        if @dropdown_item.item_type == 'external_link'
          @dropdown_item.link_text.update!(link_text_params)
        end        
        flash[:success] = 'Dropdown item was successfully updated'
        format.html { redirect_to admin_dropdown_item_url(@dropdown_item) }
        format.json { render :show, status: :ok, location: @dropdown_item }
      rescue Exception, DropdownItem::ExclusiveArcError => e
        flash[:danger] = "Error: #{e.message}"
        format.html { render :edit }
        format.json { render json: @dropdown_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dropdown_items/1
  # DELETE /dropdown_items/1.json
  def destroy
    @dropdown = @dropdown_item.dropdown
    @dropdown_item.destroy
    respond_to do |format|
      flash[:success] = 'dropdown item was successfully deleted'
      format.html { redirect_to admin_dropdown_url(@dropdown) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dropdown_item
      @dropdown_item = DropdownItem.find(params[:id])
    end

    def set_new
      @dropdown = Dropdown.find(params[:dropdown_id])
      @dropdown_item = DropdownItem.new
      @dropdown_item.item_type = params[:item_type].present? ? params[:item_type] : nil 
      @dropdown_item.dropdown = @dropdown
      if @dropdown_item.item_type && (@dropdown_item.item_type == 'external_link')
        @dropdown_item.link_text = @dropdown_item.item_type == 'external_link' ? LinkText.new(http_https: 'https') : LinkText.new
      end
    end

    def link_text_params
      params.require(:link_text).permit(:site_id,:http_https,:link,:body,:css_classes,:test_text,:new_window)
    end

    # Never trust parameters from the scary internet, only allow the white dropdown through.
    def dropdown_item_params
      params.require(:dropdown_item).permit(:name,:label,:dropdown_id,:css_classes,:item_type,:page_id,:category_id,:link_text_id,:dropdown_item_css)
    end
end

app/views/admin/dropdown_items/_form.html.erb
<% if @dropdown_item.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
		<%= pluralize(@dropdown_item.errors.count, "error") %> prohibited this page from being saved:
	</div>
  <ul>
  <% @dropdown_item.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :dropdown_id %>
<%= f.hidden_field :item_type %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :label %>
	<%= f.text_field :label, :class => "form-control" %>
</div>
<%= render partial: "form_#{@dropdown_item.item_type}", locals: {f:f} %> 

app/views/admin/dropdown_items/_form_category_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the dropdown item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="container_row_css_classes"><%= f.label :css_classes %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @dropdown.css_classes ? @dropdown.added_css_classes : '', :class => "form-control" %>
</div>

<div class="form-bar">
	<%= f.label :category_id %>
	<%= f.select :category_id, Category.where("site_id = ?", @site.id).order('name asc').collect { |c| [c.name, c.id] }, {prompt: 'Please Select'}, :class => "form-control" %>
</div>

app/views/admin/dropdown_items/_form_external_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the dropdown item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="dropdown_item_css_classes"><%= f.label :css_classes, "CSS space separated class names" %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @dropdown_item.css_classes ? @dropdown_item.added_css_classes : '', :class => "form-control" %>
</div>

<%= fields_for @dropdown_item.link_text do |link| %>
  <%= render partial: "admin/link_texts/form", locals: {link:link,link_text:@dropdown_item.link_text} %>
<% end %>

app/views/admin/dropdown_items/_form_page_link.html.erb
<div class="bs-help">
	<p>Use Bootstrap CSS classes plus your own to set the look and behavior of the dropdown item.</p> 
	<p>Class nav-item is automatically included.</p>
</div>
<label for="container_row_css_classes"><%= f.label :css_classes %></label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">nav-item</span>
  </div>
  <%= f.text_field :css_classes, value: @dropdown_item.css_classes ? @dropdown_item.added_css_classes : '', :class => "form-control" %>
</div>

<div class="form-bar">
	<%= f.label :page_id %>
	<%= f.select :page_id, Page.where("site_id = ? and id not in (select page_id from dropdown_items where dropdown_id = ?)", @site.id, @dropdown_item.dropdown.id).order('name asc').collect { |c| [c.name, c.id] }, {prompt: 'Please Select'}, :class => "form-control" %>
</div>

app/views/admin/dropdown_items/_index.html.erb
<div class="row">
	<div class="col-md-12">
	  <h2>Dropdown Items</h2>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Position</th>
					<th>Name</th>
					<th>Type</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody id="dropdown_items" data-sort-items-url="<%= sort_admin_dropdown_items_url %>">
<% @dropdown_items.order('position asc').each do |dropdown_item| %>
        <tr class="dropdown_items" id="dropdown_item_<%= dropdown_item.id %>">
        	<td><span class="handle"><i class="icon-up-hand"></i></span></td>
          <td><%= link_to raw(dropdown_item.name), admin_dropdown_item_path(dropdown_item) %></td>
          <td><%= link_to dropdown_item.item_type.capitalize.sub(/_/,' '), admin_dropdown_item_path(dropdown_item) %></td>
          <td><%= link_to raw('<i class="icon-zoom-in"></i>'), admin_dropdown_item_path(dropdown_item) %></td>
          <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_admin_dropdown_item_path(dropdown_item) %></td>
          <td><%= link_to raw('<i class="icon-trash"></i>'), admin_dropdown_item_path(dropdown_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
<% end %>
				<%= raw('<tr><td colspan="6">No items for this list</td></tr>') unless @dropdown_items.count > 0 %>
			</tbody>
		</table>
		<%= link_to new_admin_dropdown_item_path(dropdown_id: @dropdown.id) do %>
			<button type="button" class="btn  btn-outline-secondary btn-med"><i class="icon-plus"></i> New Dropdown Item</button>
		<% end %>
	</div>
</div>

app/views/admin/dropdown_items/edit.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>Edit <%= @dropdown_item.name %></h1>
		</div>
		<%= form_for([:admin, @dropdown_item],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Save
			<% end %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_dropdown_item_path(@dropdown_item)) %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@dropdown_item) %>
	</div>
</div>

app/views/admin/dropdown_items/index.html.erb
<%= render partial: 'index' %>

app/views/admin/dropdown_items/new.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>New <%= @dropdown_item.item_type ? @dropdown_item.item_type.capitalize.sub(/_/,' ') : nil %> Dropdown Item</h1>
		</div>
<% if @dropdown_item.item_type %>
		<%= form_for([:admin, @dropdown_item],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Create
			<% end %>
			<%= link_to new_admin_dropdown_item_path do %>
				<button type="button" class="btn  btn-outline-secondary btn-med btn-right"><i class="icon-cancel"></i> Cancel</button>
			<% end %>
		<% end %>
<% else %>
		<div class="bs-help">
			<h3>Dropdown Item types</h3>
			<div><p><strong>Page link: </strong>Creates a menu item for a specific page such as Home, About, Blog, etc.</p>
			<%= link_to new_admin_dropdown_item_path(dropdown_id: @dropdown.id, item_type: 'page_link') do %>
				<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New Page Link Item</button>
			<% end %>
			</div>
			<hr/>
			<div><p><strong>Category link: </strong>Creates a menu item for a specific category.</p> 
				<%= link_to new_admin_dropdown_item_path(dropdown_id: @dropdown.id, item_type: 'category_link') do %>
					<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New Category Link Item</button>
				<% end %>
			</div>
			<hr/>
			<div><p><strong>External link: </strong>Creates a menu item for a specific category.</p> 
				<%= link_to new_admin_dropdown_item_path(dropdown_id: @dropdown.id, item_type: 'external_link') do %>
					<button type="button" class="btn  btn-outline-secondary btn-sm"><i class="icon-plus"></i> New External Link Item</button>
				<% end %>
			</div>
			<hr/>
			<%= link_to admin_dropdown_path(@dropdown) do %>
				<button type="button" class="btn  btn-outline-secondary btn-med btn-right"><i class="icon-cancel"></i> Cancel</button>
			<% end %>
		</div>
	<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@dropdown_item,[@dropdown]) %>
	</div>
</div>

app/views/admin/dropdown_items/show.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
			<h1><%= @dropdown_item.name %></h1>
		</div>	
		<%= object_table(@dropdown_item) %>
		<%= link_to edit_admin_dropdown_item_path(@dropdown_item) do %>
			<button type="submit" class="btn  btn-outline-secondary"><i class="icon-pencil"></i> Edit</button>
		<% end %>
		&nbsp;&nbsp;<%= link_to admin_dropdown_item_path(@dropdown_item), method: :delete, data: { confirm: "Delete dropdown_item?" } do %>
			<button type="submit" class="btn btn-danger"><i class="icon-trash"></i> Delete</button>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@dropdown_item,[@dropdown_item.dropdown]) %>
	</div>
</div>