config/routes.rb
Rails.application.routes.draw do

  resources :rental_bookings
  resources :countries
  resources :contacts
  resources :calendars do
    member do
      get :export
    end
  end

#####################################
# begin preview namespace
#####################################
  namespace :preview do

  end

#####################################
# begin admin namespace
#####################################

  namespace :admin do
    get '/' => 'admins#index'
    get 'login' => 'admin_sessions#new'
    get 'documents/(:document_url)' => 'documents#show', :document_url => /\S+/
    get 'documents' => 'documents#index'
    resources :admin_addresses
    resources :admins
    resources :admins_sites
    resources :admin_sessions
    resources :article_posts do
      collection do
        post 'sort'
      end
    end
    resources :articles do
      member do
        patch 'category'
      end
    end
    resources :authors
    resources :article_authors
    resources :artists
    resources :admins_sites
    resources :blog_posts do
      collection do
        post 'sort'
      end
    end
    resources :blogs do
      member do
        patch 'category'
      end
    end
    resources :bookings
    resources :booking_transactions
    resources :calendars do
      member do
        get :import
      end
    end
    resources :carousels
    resources :carousel_slides do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :categories do
      member do
        patch 'image'
      end
      member do
        patch 'article'
      end
    end
    resources :content_group_clones, only: [:new,:create]
    resources :content_groups do
      member do
        patch 'category'
      end
    end
    resources :content_admins do
      collection do
        post 'sort'
      end
    end
    resources :content_group_items do
      collection do
        post 'sort'
      end
    end
    resources :content_group_text_items do
      collection do
        post 'sort'
      end
    end
    resources :container_clones, only: [:new,:create]
    resources :containers
    resources :containers_pages do
      collection do
        post 'sort'
      end
    end
    resources :container_rows do
      collection do
        post 'sort'
      end
    end
    resources :designers
    resources :domains
    resources :dropdowns
    resources :dropdown_items do
      collection do
        post 'sort'
      end
    end
    resources :errors
    resources :images do
      member do
        patch 'category'
      end
    end
    resources :image_batches
    resources :image_batch_images
    resources :image_batch_uploads, only: [:create]
    resources :image_crops
    resources :image_optimizations
    resources :image_previews
    resources :image_publishes, only: [:create]
    resources :image_watermarks
    resources :image_groups
    resources :image_group_items do
      collection do
        post 'sort'
      end
      collection do
        get 'edit_all'
      end
    end
    resources :image_group_uploads
    resources :list_group_items do
      collection do
        post 'sort'
      end
    end
    resources :list_group_clones, only: [:new,:create]
    resources :list_groups
    resources :mail_servers
    resources :mail_templates
    resources :media  do
      member do
        patch 'category'
      end
    end
    resources :navigation_items do
      collection do
        post 'sort'
      end
    end
    resources :navigations
    resources :palettes
    resources :palette_colors
    resources :pages
    resources :payment_gateways
    resources :payment_methods
    resources :payment_types
    resources :rental_booking_instructions
    resources :rental_payment_methods do
      collection do
        post 'sort'
      end
    end
    resources :rentals
    resources :row_columns do
      collection do
        post 'sort'
      end
    end
    resources :site_tags do
      collection do
        post 'sort'
      end
    end
    resources :sites
    resources :songs
    resources :themes do
      member do
        get 'edit_scss_production'
      end
      member do
        get 'edit_scss_workspace'
      end
      member do
        put 'sync_css'
      end
    end
    resources :theme_colors
    resources :theme_icons
    resources :user_addresses
    resources :users
    resources :videos
    resources :watermarks
  end

  #####################################
  # end admin namespace
  #####################################

  resources :media
  resources :posts
  resources :artists
  resources :authors
  resources :errors
  resources :images
  resources :users

  # Added to match before :nice_url for pages
  get '/rails/active_storage/blobs/:signed_id/*filename(.:format)' => 'active_storage/blobs#show'
  get '/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)' => 'active_storage/representations#show'
  get '/rails/active_storage/disk/:encoded_key/*filename(.:format)' => 'active_storage/disk#show'
  put '/rails/active_storage/disk/:encoded_token(.:format)' => 'active_storage/disk#update'
  post '/rails/active_storage/direct_uploads(.:format)' => 'active_storage/direct_uploads#create'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/articles' => 'articles#index'
  get '/articles/(:content_url)' => 'articles#show', :content_url => /\S+/
  get '/image_previews/*' => 'pages#static_asset'
  get '/documents/*' => 'pages#static_asset'
  get '/(:nice_url)' => 'pages#show', :nice_url => /\S+/
  root 'pages#show'

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :site
	has_many :containers
	has_many :carousel_slides
	has_many :image_group_items
 	has_many :categories_images
 	has_many :categories, through: :categories_images
	has_one_attached :image
  has_many :image_previews

  after_destroy :clean_up

  def clean_up
    FileUtils.rm Dir.glob("#{Rails.root}/public/image_previews/*_#{self.id}.*")
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :category, :proxy]
  before_action :set_category, only: [:category]

  layout 'admins'

  # GET /images
  # GET /images.json
  def index
    @images = Image.where(site_id: @site.id)
  end

  # GET /images/1
  # GET /images/1.json
  def show
    unless @image.image.attached?
      @image_preview = ImagePreview.find_by(image_id: @image.id, preview_type: 'original')
      respond_to do |format|
        if @image_preview
          format.html { redirect_to admin_image_preview_url(@image) }
        else
          format.html { redirect_to new_admin_image_preview_url(image_id: @image.id) }
        end
      end
    end
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  def category
    respond_to do |format|
      format.js do
        if @category
          if @image.categories.include?(@category)
            @image.categories.delete(@category)
          else
            @image.categories << @category
          end
        end
      end
    end
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    respond_to do |format|
      if @image.save
        flash[:success] = 'Image was successfully created.'
        format.html { redirect_to new_admin_image_preview_url(image_id: @image.id) }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      begin
        if @image.update(image_params)
          flash[:success] = 'Image was successfully updated.'
          format.html { redirect_to admin_image_url(@image) }
          format.js
          format.json { render :show, status: :ok, location: @image }
        else
          format.html { render :edit }
          format.js
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      rescue Exception => e
        flash[:danger] = "Oops! Something went wrong: #{e.message}"
        format.html { render :edit }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    respond_to do |format|
      begin
        if @image.destroy
          flash[:success] = 'Image was successfully removed.'
          format.html { redirect_to admin_images_url }
          format.json { head :no_content }
        end
      rescue Exception => e
        flash[:danger] = "Oops! Something went wrong: #{e.message}"
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      # @image = Image.find_by(id: params[:id],site_id: @site.id)
      @image = Image.find(params[:id])
      redirect_to admin_errors_url(error_template: '403') unless @image
    end

    def set_category
      @category = params[:category_id].present? ? Category.find(params[:category_id]) : nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:site_id,:name,:caption,:copyright_year,:copyright_by,:description,:image,:image_preview_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper

	require 'json'

	def optimize_td(image)
		html = ""
		size = image.image.blob.byte_size ? image.image.blob.byte_size : 0
		if size > 500000
			html = "<td style=\"background-color:#ffb399\">"
			html +=	link_to raw("<icon class=\"icon-emo-angry\"></icon> #{size}"), edit_admin_image_optimization_path(image)
			html +=	"</td>"
		elsif size > 300000
			html = "<td style=\"background-color:#ffb366\">"
			html += link_to raw("<icon class=\"icon-emo-surprised\"></icon> #{size}"), edit_admin_image_optimization_path(image)
			html +=	"</td>"
		elsif size > 175000
			html = "<td style=\"background-color:#ffffb3\">"
			html +=	link_to raw("<icon class=\"icon-emo-unhappy\"></icon> #{size}"), edit_admin_image_optimization_path(image)
			html +=	"</td>"
		else
			html = "<td style=\"background-color:#ccffcc\">"
			html +=	raw("<icon class=\"icon-emo-happy\"></icon> #{size}")
			html +=	"</td>"
		end
		html.html_safe
	end

	def optimize_div(image)
		max_width = image.image.blob.metadata['width']
		html = ""
		message = image.quality ? " This image has been optimized." : ""
		size = image.image.blob.byte_size ? image.image.blob.byte_size : 0
		if size > 500000
			html = "<div class=\"image-bytes-angry\" style=\"max-width: #{max_width}px\">"
			html +=	raw("<icon class=\"icon-emo-angry\"></icon> #{size} bytes. #{message}")
		elsif size > 300000
			html = "<div class=\"image-bytes-surprised\" style=\"max-width: #{max_width}px\">"
			html += raw("<icon class=\"icon-emo-surprised\" style=\"max-width: #{max_width}px\"></icon> #{size} bytes. #{message}")
		elsif size > 175000
			html = "<div class=\"image-bytes-unhappy\">"
			html +=	raw("<icon class=\"icon-emo-unhappy\" style=\"max-width: #{max_width}px\"></icon> #{size} bytes. #{message}")
		else
			html = "<div class=\"image-bytes-happy\" style=\"max-width: #{max_width}px\">"
			html +=	raw("<icon class=\"icon-emo-happy\"></icon> #{size} bytes. #{message}")
		end
		html +=	"</div>"
		html += "<h6>Source: #{image.image.blob.filename}</h6>"
		image_hash = JSON.parse(image.image.blob.metadata.to_json)
		html += "<h6>Max dimensions: width #{image_hash['width']}px, height #{image_hash['height']}px</h6>"
		html.html_safe
	end

	def file_size_div(size, max_width)
		html = ""
		if size > 500000
			html = "<div class=\"image-bytes-angry\" style=\"max-width: #{max_width}px\">"
			html +=	raw("<icon class=\"icon-emo-angry\"></icon> #{size} bytes.")
		elsif size > 300000
			html = "<div class=\"image-bytes-surprised\" style=\"max-width: #{max_width}px\">"
			html += raw("<icon class=\"icon-emo-surprised\"></icon> #{size} bytes.")
		elsif size > 175000
			html = "<div class=\"image-bytes-unhappy\" style=\"max-width: #{max_width}px\">"
			html +=	raw("<icon class=\"icon-emo-unhappy\"></icon> #{size} bytes.")
		else
			html = "<div class=\"image-bytes-happy\" style=\"max-width: #{max_width}px\">"
			html +=	raw("<icon class=\"icon-emo-happy\"></icon> #{size} bytes.")
		end
		html +=	"</div>"
		html.html_safe
	end

  def image_width_options(max_width)
  	options = {}
  	if max_width.to_i >= 1915
  		options['1920px Full width HD Displays'] = '1920'
  		options['1600px'] = '1600'
  		options['1366px'] = '1366'
  		options['1024px'] = '1024'
  	elsif max_width.to_i >= 1590
			options['1600px'] = '1600'
			options['1366px'] = '1366'
			options['1024px'] = '1024'
 		elsif max_width.to_i >= 1356
			options['1366'] = '1366'
			options['1024px'] = '1024'
	 	elsif max_width.to_i >= 1014
			options['1024px'] = '1024'
 		end
 		options['768px'] = '768'
 		return options
  end

	def src_sets(image,parent,img_class=nil)
		alt = parent && parent.name =~ /\S+/ ? parent.name : image.name
		title = parent && parent.caption =~ /\S+/ ? parent.caption : image.caption
		if image && image.image.attached?
			css = img_class ? img_class : 'img-fluid'
			srcset = []
			img_src = url_for(image.image)
			if image.max_width.to_i >= 1920
				srcset << [url_for(image.image.variant(resize: '1600x1600')), "1600w"]
				srcset << [url_for(image.image.variant(resize: '1366x1366')), "1366w"]
				srcset << [url_for(image.image.variant(resize: '1024x1024')), "1024w"]
			elsif image.max_width.to_i >= 1600
				srcset << [url_for(image.image.variant(resize: '1366x1366')), "1366w"]
				srcset << [url_for(image.image.variant(resize: '1024x1024')), "1024w"]
			elsif image.max_width.to_i >= 1366
				srcset << [url_for(image.image.variant(resize: '1024x1024')), "1024w"]
			end
			srcset << [url_for(image.image.variant(resize: '768x768')), "768w"]
			srcset << [url_for(image.image.variant(resize: '576x576')), "576w"]
			image_tag(img_src, srcset: srcset, alt: "#{alt}", title: "#{title}",  class: css )
		end
	end


end

app/views/admin/images/_form.html.erb
<% if @image.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
		<%= pluralize(@image.errors.count, "error") %> prohibited this page from being saved:
	</div>
  <ul>
  <% @image.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :site_id, value: @site.id %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :caption %>
	<%= f.text_field :caption, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :copyright_year %>
	<%= f.text_field :copyright_year, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :copyright_by %>
	<div class="input-group mb-3">
  	<div class="input-group-prepend">
    	<span class="input-group-text" id="inputGroup-sizing-default"><icon class="icon-copyright"></icon></span>
    </div>
		<%= f.text_field :copyright_by, :class => "form-control" %>
	</div>
</div>
<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, 'data-provider': :summernote, :class => "form-control" %>
</div>

app/views/admin/images/_image_select.html.erb
<div class="row">
	<div class="col">
		<hr/>
		<h4>Select Image:</h4>
	</div>
</div>
<div class="row">
	<%  @site.images.order('name asc').each do |image| %>
	<% if image.image.attached? %>
	<div class="col-md">
		<div class="card select-image<%= ' image-selected' if selected_id && image.id == selected_id %>" id="image_select_<%= image.id %>" style="width: 150px;">
		  <%= image_tag url_for(image.image.variant(resize: "150x150")), :class => "card-img-top" %>
		  <div class="card-body">
		    <h5 class="card-title" id="card_title_<%= image.id %>"><%= image.name %></h5>
		    <button type="button" id="image_button_<%= image.id %>" class="btn btn-outline-secondary btn-sm image-select">Select</button>
		  </div>
		</div>
	</div>
	<% end %>
<% end %>
</div>

app/views/admin/images/_image_select_table.html.erb
    <h4>Select Image:</h4>
    <table id="image_table" class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th></th>
          <th>Name</th>
          <th>Category</th>
          <th>Group</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
<%
images = @site.images.order('name asc')
images.order('name asc').each do |image|
  next unless image.image.attached?
  image_group = image.image_group_items.any? ? image.image_group_items.first.image_group.name : 'n/a'
  image_category = image.categories.any? ? image.categories.first.name : 'n/a'
%>
        <tr class="select-image<%= ' image-selected' if content.image_id && image.id == content.image_id %>" id="image_select_<%= image.id %>">
          <td><%= image.id %></td>
          <td>
            <%= image_tag(image.image.variant(resize: "100x100"), id: "image_#{image.id}") %>
          </td>
          <td><%= image.name %></td>
          <td><%= image_category %></td>
          <td><%= image_group %></td>
          <td>
            <button type="button" id="image_button_<%= image.id %>" class="btn btn-outline-secondary btn-sm">Select</button>
          </td>
        </tr>
<% end %>
      <%= raw('<tr><td colspan="5">No images published.</td></tr>') if images.count == 0 %>
      </tbody>
    </table>
    <%= f.hidden_field :image_id, id: "hidden_image_field" %>
    <h4>Selected:</h4>
    <div style="border: solid 1px #000;padding:25px;max-width:152px;">
<% if content.image && content.image.image.attached? %>
      <%= image_tag content.image.image.variant(resize: "100x100"), id: "image_selected", style: 'margin-right:auto;margin-left:auto;' %>
<% else %>
      <image id="image_selected" src="" style="display:none;" />
<% end %>
    </div>
    <p id="image_text"><%= content.image ? content.image.name : "Not selected" %></p>

app/views/admin/images/_watermark.html.erb
<script>

</script>

app/views/admin/images/category.js.erb
$("#categories").html("<%= escape_javascript(render(:partial => 'admin/categories_images/index')) %>");

app/views/admin/images/edit.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>Edit <%= @image.name %></h1>
		</div>
		<%= form_for([:admin, @image],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Save
			<% end %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_image_path(@image)) %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@image) %>
	</div>
</div>

app/views/admin/images/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
		  <h1>Images</h1>
		</div>
		<table id="image_index" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th>Souce</th>
					<th>Date</th>
					<th>Size</th>
          <th>Published?</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
<% @images.where(site_id: @site.id).order('name asc').each do |image| %>
        <tr>
        	<td>
  <% if image.image.attached? %>
        		<%= link_to image_tag(image.image.variant(resize: "100x100")), admin_image_path(image) %>
  <% elsif image.image_previews.any?
    preview = ImagePreview.find_by(image_id: image.id,preview_type: 'original')
  %>
            <%= link_to image_tag("/image_previews/original_#{image.id}.#{preview.file_extention}", style: 'max-width: 100px'), admin_image_path(image) %>
  <% end %>
          </td>
          <td><%= link_to raw(image.name), admin_image_path(image) %></td>
          <td><%= link_to image.image.filename, admin_image_path(image) if image.image.attached? %></td>
          <td><%= link_to image.created_at.strftime("%Y-%m-%d"), admin_image_path(image) %></td>
  <% if image.image.attached? %>
  				<%= optimize_td(image) %>
          <td>Yes</td>
  <% elsif image.image_previews.any? %>
          <td><%= link_to raw("<icon class=\"icon-cog\"></icon> Unpublished image"), admin_image_preview_path(image) %></td>
          <td>No</td>
  <% else %>
  				<td><%= link_to raw("<icon class=\"icon-upload\"></icon> Upload"), new_admin_image_preview_path(image_id: image.id) %></td>
          <td>No</td>
  <% end %>
          <td><%= link_to raw('<i class="icon-zoom-in"></i>'), admin_image_path(image) %></td>
          <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_admin_image_path(image) %></td>
          <td><%= link_to raw('<i class="icon-trash"></i>'), admin_image_path(image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
<% end %>
			<%= raw('<tr><td colspan="7">No images uploaded.</td></tr>') if @images.count == 0 %>
			</tbody>
		</table>
		<%= link_to new_admin_image_path do %>
			<button type="button" class="btn  btn-outline-secondary btn-med"><i class="icon-plus"></i> New Image</button>
		<% end %>
    <%= link_to new_admin_image_batch_path do %>
      <button type="button" class="btn  btn-outline-secondary btn-med"><i class="icon-plus"></i> New Image Batch</button>
    <% end %>
	</div>
</div>

app/views/admin/images/new.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-headerr">
		  <h1>New Image</h1>
		</div>
		<%= form_for([:admin, @image],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<%= render partial: 'form', locals: {f:f} %>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				Next <icon class="icon-right-big"></icon>
			<% end %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_images_path) %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@image) %>
	</div>
</div>

app/views/admin/images/show.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
			<h1><%= @image.name %></h1>
		</div>
		<h3>Status: Published</h3>
		<div class="image-original">
			<%= image_tag url_for(@image.image), class: 'img-fluid' %>
		</div>
		<%= optimize_div(@image) %>
		<div class="image-buttons">
			<%= link_to new_admin_image_preview_path(image_id: @image.id) do %>
			<button type="button" class="btn btn-outline-secondary btn-sm">
				<icon class="icon-upload"></icon> Upload/Replace Image
			</button>
			<% end %>
<% if @image.image.attached? && @image.image_previews.any? %>
      <%= link_to admin_image_preview_path(@image) do %>
      	<button type="button" class="btn btn-outline-secondary btn-sm">
      		<icon class="icon-cog"></icon> Continue Processing New Version
      	</button>
      <% end %>
<% end %>
		</div>
		<%= object_table(@image) %>
		<%= link_to edit_admin_image_path(@image) do %>
			<button type="button" class="btn  btn-outline-secondary"><i class="icon-pencil"></i> Edit</button>
		<% end %>
		&nbsp;&nbsp;<%= link_to admin_image_path(@image), method: :delete, data: { confirm: "Delete image?" } do %>
			<button type="button" class="btn btn-danger"><i class="icon-trash"></i> Delete</button>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@image) %>
	</div>
</div>
<div id="categories">
	<%= render partial: 'admin/categories_images/index' %>
</div>

app/views/admin/images/update.js.erb
$("#image_<%= @image.id %>").html("<%= escape_javascript(render(:partial => 'admin/image_batch_images/show', locals: {image: @image} )) %>");
$("#image_card_<%= @image.id %>").css({borderColor:'green'});
$("#image_card_<%= @image.id %>").css({backgroundColor:'#e7f3f3'});
setTimeout(() => { $("#image_card_<%= @image.id %>").css({backgroundColor:'#fff'}) }, 1000);

app/views/admin/images/upload.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
		  <h1>Upload <%= @image.name %></h1>
		</div>
		<%= form_for([:admin, @image],:html => {:role => 'form', :class => "formFor"}) do |f| %>
			<div class="form-group">
				<%= f.label :image %>			
				<%= f.file_field(:image, multiple: false, direct_upload: true, class: 'form-control-file') %>
			</div>
			<hr />
			<%= button_tag(type: 'submit', class:"btn  btn-outline-secondary btn-med") do %>
				<i class="icon-ok"></i>
				Upload
			<% end %>
			<%= link_to(raw('<button type="button" class="btn  btn-outline-secondary btn-med btn-right">
				<i class="icon-cancel"></i>
		   	 	Cancel</button>'), admin_image_path(@image)) %>
		<% end %>
	</div>
	<div class="col-md-3">
		<%= operations_menu(@image) %>
	</div>
</div>